
package wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Interface1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Interface1 {


    /**
     * 
     * @param origin
     * @param destination
     * @return
     *     returns wsclient.ArrayOfStep
     */
    @WebMethod(action = "http://tempuri.org/Interface1/getItinerary")
    @WebResult(name = "getItineraryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getItinerary", targetNamespace = "http://tempuri.org/", className = "wsclient.GetItinerary")
    @ResponseWrapper(localName = "getItineraryResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetItineraryResponse")
    public ArrayOfStep getItinerary(
        @WebParam(name = "origin", targetNamespace = "http://tempuri.org/")
        String origin,
        @WebParam(name = "destination", targetNamespace = "http://tempuri.org/")
        String destination);

}
